const abi = [
  {
     "inputs":[
        {
           "internalType":"address[]",
           "name":"_stables",
           "type":"address[]"
        },
        {
           "internalType":"address",
           "name":"_dev",
           "type":"address"
        }
     ],
     "stateMutability":"nonpayable",
     "type":"constructor"
  },
  {
     "anonymous":false,
     "inputs":[
        {
           "indexed":true,
           "internalType":"address",
           "name":"owner",
           "type":"address"
        },
        {
           "indexed":true,
           "internalType":"address",
           "name":"spender",
           "type":"address"
        },
        {
           "indexed":false,
           "internalType":"uint256",
           "name":"value",
           "type":"uint256"
        }
     ],
     "name":"Approval",
     "type":"event"
  },
  {
     "anonymous":false,
     "inputs":[
        {
           "indexed":false,
           "internalType":"address",
           "name":"who",
           "type":"address"
        },
        {
           "indexed":false,
           "internalType":"uint256",
           "name":"amountTokensErased",
           "type":"uint256"
        }
     ],
     "name":"ErasedHoldings",
     "type":"event"
  },
  {
     "anonymous":false,
     "inputs":[
        {
           "indexed":false,
           "internalType":"address",
           "name":"_from",
           "type":"address"
        },
        {
           "indexed":false,
           "internalType":"address",
           "name":"_to",
           "type":"address"
        },
        {
           "indexed":false,
           "internalType":"uint256",
           "name":"amountFROM",
           "type":"uint256"
        },
        {
           "indexed":false,
           "internalType":"uint256",
           "name":"amountTO",
           "type":"uint256"
        }
     ],
     "name":"ExchangeToken",
     "type":"event"
  },
  {
     "anonymous":false,
     "inputs":[
        {
           "indexed":false,
           "internalType":"uint256",
           "name":"amountTokensErased",
           "type":"uint256"
        }
     ],
     "name":"GarbageCollected",
     "type":"event"
  },
  {
     "anonymous":false,
     "inputs":[
        {
           "indexed":true,
           "internalType":"address",
           "name":"previousOwner",
           "type":"address"
        },
        {
           "indexed":true,
           "internalType":"address",
           "name":"newOwner",
           "type":"address"
        }
     ],
     "name":"OwnershipTransferred",
     "type":"event"
  },
  {
     "anonymous":false,
     "inputs":[
        {
           "indexed":false,
           "internalType":"uint256",
           "name":"previousPrice",
           "type":"uint256"
        },
        {
           "indexed":false,
           "internalType":"uint256",
           "name":"currentPrice",
           "type":"uint256"
        },
        {
           "indexed":false,
           "internalType":"uint256",
           "name":"totalSupply",
           "type":"uint256"
        }
     ],
     "name":"PriceChange",
     "type":"event"
  },
  {
     "anonymous":false,
     "inputs":[
        {
           "indexed":false,
           "internalType":"address",
           "name":"executor",
           "type":"address"
        },
        {
           "indexed":false,
           "internalType":"bool",
           "name":"isExecutor",
           "type":"bool"
        }
     ],
     "name":"SetExecutor",
     "type":"event"
  },
  {
     "anonymous":false,
     "inputs":[
        {
           "indexed":false,
           "internalType":"address",
           "name":"Contract",
           "type":"address"
        },
        {
           "indexed":false,
           "internalType":"bool",
           "name":"exempt",
           "type":"bool"
        }
     ],
     "name":"SetFeeExemption",
     "type":"event"
  },
  {
     "anonymous":false,
     "inputs":[
        {
           "indexed":false,
           "internalType":"address",
           "name":"stable",
           "type":"address"
        },
        {
           "indexed":false,
           "internalType":"bool",
           "name":"exempt",
           "type":"bool"
        }
     ],
     "name":"SetStableToken",
     "type":"event"
  },
  {
     "anonymous":false,
     "inputs":[
        {
           "indexed":false,
           "internalType":"uint256",
           "name":"totalSupply",
           "type":"uint256"
        },
        {
           "indexed":false,
           "internalType":"uint256",
           "name":"price",
           "type":"uint256"
        },
        {
           "indexed":false,
           "internalType":"uint256",
           "name":"timestamp",
           "type":"uint256"
        }
     ],
     "name":"TokenActivated",
     "type":"event"
  },
  {
     "anonymous":false,
     "inputs":[
        {
           "indexed":false,
           "internalType":"uint256",
           "name":"assetsReceived",
           "type":"uint256"
        },
        {
           "indexed":false,
           "internalType":"address",
           "name":"recipient",
           "type":"address"
        }
     ],
     "name":"TokenPurchased",
     "type":"event"
  },
  {
     "anonymous":false,
     "inputs":[
        {
           "indexed":false,
           "internalType":"uint256",
           "name":"amountCLIMB",
           "type":"uint256"
        },
        {
           "indexed":false,
           "internalType":"uint256",
           "name":"assetsRedeemed",
           "type":"uint256"
        },
        {
           "indexed":false,
           "internalType":"address",
           "name":"recipient",
           "type":"address"
        }
     ],
     "name":"TokenSold",
     "type":"event"
  },
  {
     "anonymous":false,
     "inputs":[
        {
           "indexed":false,
           "internalType":"uint256",
           "name":"assetsReceived",
           "type":"uint256"
        },
        {
           "indexed":false,
           "internalType":"address",
           "name":"recipient",
           "type":"address"
        }
     ],
     "name":"TokenStaked",
     "type":"event"
  },
  {
     "anonymous":false,
     "inputs":[
        {
           "indexed":true,
           "internalType":"address",
           "name":"from",
           "type":"address"
        },
        {
           "indexed":true,
           "internalType":"address",
           "name":"to",
           "type":"address"
        },
        {
           "indexed":false,
           "internalType":"uint256",
           "name":"value",
           "type":"uint256"
        }
     ],
     "name":"Transfer",
     "type":"event"
  },
  {
     "anonymous":false,
     "inputs":[
        {
           "indexed":false,
           "internalType":"address",
           "name":"newOwner",
           "type":"address"
        }
     ],
     "name":"TransferOwnership",
     "type":"event"
  },
  {
     "anonymous":false,
     "inputs":[
        {
           "indexed":false,
           "internalType":"address",
           "name":"updatedDev",
           "type":"address"
        }
     ],
     "name":"UpdateDevAddress",
     "type":"event"
  },
  {
     "anonymous":false,
     "inputs":[
        {
           "indexed":false,
           "internalType":"uint256",
           "name":"updatedSellFee",
           "type":"uint256"
        },
        {
           "indexed":false,
           "internalType":"uint256",
           "name":"updatedMintFee",
           "type":"uint256"
        },
        {
           "indexed":false,
           "internalType":"uint256",
           "name":"updatedTransferFee",
           "type":"uint256"
        }
     ],
     "name":"UpdateFees",
     "type":"event"
  },
  {
     "anonymous":false,
     "inputs":[
        {
           "indexed":false,
           "internalType":"uint256",
           "name":"updatedDevShare",
           "type":"uint256"
        },
        {
           "indexed":false,
           "internalType":"uint256",
           "name":"updatedLiquidityShare",
           "type":"uint256"
        }
     ],
     "name":"UpdateShares",
     "type":"event"
  },
  {
     "anonymous":false,
     "inputs":[
        {
           "indexed":false,
           "internalType":"uint256",
           "name":"newSlippage",
           "type":"uint256"
        }
     ],
     "name":"UpdateTokenSlippage",
     "type":"event"
  },
  {
     "inputs":[
        
     ],
     "name":"ActivateToken",
     "outputs":[
        
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"allStables",
     "outputs":[
        {
           "internalType":"address[]",
           "name":"",
           "type":"address[]"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"address",
           "name":"holder",
           "type":"address"
        },
        {
           "internalType":"address",
           "name":"spender",
           "type":"address"
        }
     ],
     "name":"allowance",
     "outputs":[
        {
           "internalType":"uint256",
           "name":"",
           "type":"uint256"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"address",
           "name":"spender",
           "type":"address"
        },
        {
           "internalType":"uint256",
           "name":"amount",
           "type":"uint256"
        }
     ],
     "name":"approve",
     "outputs":[
        {
           "internalType":"bool",
           "name":"",
           "type":"bool"
        }
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"address",
           "name":"account",
           "type":"address"
        }
     ],
     "name":"balanceOf",
     "outputs":[
        {
           "internalType":"uint256",
           "name":"",
           "type":"uint256"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"uint256",
           "name":"amount",
           "type":"uint256"
        }
     ],
     "name":"burn",
     "outputs":[
        
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"uint256",
           "name":"underlyingAmount",
           "type":"uint256"
        },
        {
           "internalType":"address",
           "name":"_stable",
           "type":"address"
        }
     ],
     "name":"burnWithUnderlying",
     "outputs":[
        
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"uint256",
           "name":"numTokens",
           "type":"uint256"
        },
        {
           "internalType":"address",
           "name":"_stable",
           "type":"address"
        }
     ],
     "name":"buy",
     "outputs":[
        {
           "internalType":"uint256",
           "name":"",
           "type":"uint256"
        }
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"address",
           "name":"recipient",
           "type":"address"
        },
        {
           "internalType":"uint256",
           "name":"numTokens",
           "type":"uint256"
        },
        {
           "internalType":"address",
           "name":"_stable",
           "type":"address"
        }
     ],
     "name":"buy",
     "outputs":[
        {
           "internalType":"uint256",
           "name":"",
           "type":"uint256"
        }
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"address",
           "name":"recipient",
           "type":"address"
        },
        {
           "internalType":"uint256",
           "name":"numTokens",
           "type":"uint256"
        },
        {
           "internalType":"address",
           "name":"_stable",
           "type":"address"
        }
     ],
     "name":"buyFor",
     "outputs":[
        {
           "internalType":"uint256",
           "name":"",
           "type":"uint256"
        }
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"calculatePrice",
     "outputs":[
        {
           "internalType":"uint256",
           "name":"",
           "type":"uint256"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"uint256",
           "name":"",
           "type":"uint256"
        }
     ],
     "name":"currentStables",
     "outputs":[
        {
           "internalType":"address",
           "name":"",
           "type":"address"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"decimals",
     "outputs":[
        {
           "internalType":"uint8",
           "name":"",
           "type":"uint8"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"dev",
     "outputs":[
        {
           "internalType":"address",
           "name":"",
           "type":"address"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"devShare",
     "outputs":[
        {
           "internalType":"uint256",
           "name":"",
           "type":"uint256"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"uint256",
           "name":"nHoldings",
           "type":"uint256"
        }
     ],
     "name":"eraseHoldings",
     "outputs":[
        
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"address",
           "name":"_from",
           "type":"address"
        },
        {
           "internalType":"address",
           "name":"_to",
           "type":"address"
        },
        {
           "internalType":"address",
           "name":"_router",
           "type":"address"
        }
     ],
     "name":"exchangeTokens",
     "outputs":[
        
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"feeDenominator",
     "outputs":[
        {
           "internalType":"uint256",
           "name":"",
           "type":"uint256"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"address",
           "name":"holder",
           "type":"address"
        }
     ],
     "name":"getValueOfHoldings",
     "outputs":[
        {
           "internalType":"uint256",
           "name":"",
           "type":"uint256"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"address",
           "name":"holder",
           "type":"address"
        }
     ],
     "name":"getValueOfHoldingsAfterTax",
     "outputs":[
        {
           "internalType":"uint256",
           "name":"",
           "type":"uint256"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"address",
           "name":"",
           "type":"address"
        }
     ],
     "name":"isExecutor",
     "outputs":[
        {
           "internalType":"bool",
           "name":"",
           "type":"bool"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"address",
           "name":"",
           "type":"address"
        }
     ],
     "name":"isFeeExempt",
     "outputs":[
        {
           "internalType":"bool",
           "name":"",
           "type":"bool"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"liquidityShare",
     "outputs":[
        {
           "internalType":"uint256",
           "name":"",
           "type":"uint256"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"mintFee",
     "outputs":[
        {
           "internalType":"uint256",
           "name":"",
           "type":"uint256"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"name",
     "outputs":[
        {
           "internalType":"string",
           "name":"",
           "type":"string"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"owner",
     "outputs":[
        {
           "internalType":"address",
           "name":"",
           "type":"address"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"price",
     "outputs":[
        {
           "internalType":"uint256",
           "name":"",
           "type":"uint256"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"renounceOwnership",
     "outputs":[
        
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"address",
           "name":"recipient",
           "type":"address"
        },
        {
           "internalType":"uint256",
           "name":"tokenAmount",
           "type":"uint256"
        },
        {
           "internalType":"address",
           "name":"_stable",
           "type":"address"
        }
     ],
     "name":"sell",
     "outputs":[
        {
           "internalType":"uint256",
           "name":"",
           "type":"uint256"
        }
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"uint256",
           "name":"tokenAmount",
           "type":"uint256"
        },
        {
           "internalType":"address",
           "name":"_stable",
           "type":"address"
        }
     ],
     "name":"sell",
     "outputs":[
        {
           "internalType":"uint256",
           "name":"",
           "type":"uint256"
        }
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"address",
           "name":"_stable",
           "type":"address"
        }
     ],
     "name":"sellAll",
     "outputs":[
        
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"sellFee",
     "outputs":[
        {
           "internalType":"uint256",
           "name":"",
           "type":"uint256"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"uint256",
           "name":"amount",
           "type":"uint256"
        },
        {
           "internalType":"address",
           "name":"_stable",
           "type":"address"
        }
     ],
     "name":"sellInWholeTokenAmounts",
     "outputs":[
        
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"address",
           "name":"executorAddress",
           "type":"address"
        },
        {
           "internalType":"bool",
           "name":"exempt",
           "type":"bool"
        }
     ],
     "name":"setExecutorAddress",
     "outputs":[
        
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"address",
           "name":"Contract",
           "type":"address"
        },
        {
           "internalType":"bool",
           "name":"exempt",
           "type":"bool"
        }
     ],
     "name":"setFeeExemption",
     "outputs":[
        
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"address",
           "name":"_stable",
           "type":"address"
        },
        {
           "internalType":"bool",
           "name":"_accept",
           "type":"bool"
        }
     ],
     "name":"setStableToken",
     "outputs":[
        
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"sharesDenominator",
     "outputs":[
        {
           "internalType":"uint256",
           "name":"",
           "type":"uint256"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"address",
           "name":"",
           "type":"address"
        }
     ],
     "name":"stables",
     "outputs":[
        {
           "internalType":"uint256",
           "name":"balance",
           "type":"uint256"
        },
        {
           "internalType":"uint8",
           "name":"index",
           "type":"uint8"
        },
        {
           "internalType":"uint8",
           "name":"decimals",
           "type":"uint8"
        },
        {
           "internalType":"bool",
           "name":"accepted",
           "type":"bool"
        },
        {
           "internalType":"bool",
           "name":"setup",
           "type":"bool"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"symbol",
     "outputs":[
        {
           "internalType":"string",
           "name":"",
           "type":"string"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"takeOutGarbage",
     "outputs":[
        
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"totalSupply",
     "outputs":[
        {
           "internalType":"uint256",
           "name":"",
           "type":"uint256"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"address",
           "name":"recipient",
           "type":"address"
        },
        {
           "internalType":"uint256",
           "name":"amount",
           "type":"uint256"
        }
     ],
     "name":"transfer",
     "outputs":[
        {
           "internalType":"bool",
           "name":"",
           "type":"bool"
        }
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"transferFee",
     "outputs":[
        {
           "internalType":"uint256",
           "name":"",
           "type":"uint256"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"address",
           "name":"sender",
           "type":"address"
        },
        {
           "internalType":"address",
           "name":"recipient",
           "type":"address"
        },
        {
           "internalType":"uint256",
           "name":"amount",
           "type":"uint256"
        }
     ],
     "name":"transferFrom",
     "outputs":[
        {
           "internalType":"bool",
           "name":"",
           "type":"bool"
        }
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"address",
           "name":"newOwner",
           "type":"address"
        }
     ],
     "name":"transferOwnership",
     "outputs":[
        
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"address",
           "name":"newDev",
           "type":"address"
        }
     ],
     "name":"updateDevAddress",
     "outputs":[
        
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"uint256",
           "name":"newSellFee",
           "type":"uint256"
        },
        {
           "internalType":"uint256",
           "name":"newMintFee",
           "type":"uint256"
        },
        {
           "internalType":"uint256",
           "name":"newTransferFee",
           "type":"uint256"
        }
     ],
     "name":"updateFees",
     "outputs":[
        
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"uint256",
           "name":"newDevShare",
           "type":"uint256"
        },
        {
           "internalType":"uint256",
           "name":"newLiquidityShare",
           "type":"uint256"
        }
     ],
     "name":"updateShares",
     "outputs":[
        
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"address",
           "name":"wallet",
           "type":"address"
        }
     ],
     "name":"volumeFor",
     "outputs":[
        {
           "internalType":"uint256",
           "name":"",
           "type":"uint256"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  }
] as const;

export default abi;