const abi = [
  {
     "type":"constructor",
     "inputs":[
        {
           "name":"_growToken",
           "type":"address",
           "internalType":"address"
        },
        {
           "name":"_stable",
           "type":"address",
           "internalType":"address"
        },
        {
           "name":"_owners",
           "type":"address[]",
           "internalType":"address[]"
        }
     ],
     "stateMutability":"nonpayable"
  },
  {
     "type":"function",
     "name":"EGGS_TO_HATCH_1MINERS",
     "inputs":[
        
     ],
     "outputs":[
        {
           "name":"",
           "type":"uint256",
           "internalType":"uint256"
        }
     ],
     "stateMutability":"view"
  },
  {
     "type":"function",
     "name":"GROW",
     "inputs":[
        
     ],
     "outputs":[
        {
           "name":"",
           "type":"address",
           "internalType":"contract IGrow"
        }
     ],
     "stateMutability":"view"
  },
  {
     "type":"function",
     "name":"MAX_VAULT_TIME",
     "inputs":[
        
     ],
     "outputs":[
        {
           "name":"",
           "type":"uint256",
           "internalType":"uint256"
        }
     ],
     "stateMutability":"view"
  },
  {
     "type":"function",
     "name":"PERCENT_BASE",
     "inputs":[
        
     ],
     "outputs":[
        {
           "name":"",
           "type":"uint256",
           "internalType":"uint256"
        }
     ],
     "stateMutability":"view"
  },
  {
     "type":"function",
     "name":"STABLE",
     "inputs":[
        
     ],
     "outputs":[
        {
           "name":"",
           "type":"address",
           "internalType":"contract IERC20"
        }
     ],
     "stateMutability":"view"
  },
  {
     "type":"function",
     "name":"calculateEggBuy",
     "inputs":[
        {
           "name":"amount",
           "type":"uint256",
           "internalType":"uint256"
        },
        {
           "name":"contractBalance",
           "type":"uint256",
           "internalType":"uint256"
        }
     ],
     "outputs":[
        {
           "name":"",
           "type":"uint256",
           "internalType":"uint256"
        }
     ],
     "stateMutability":"view"
  },
  {
     "type":"function",
     "name":"calculateEggBuySimple",
     "inputs":[
        {
           "name":"amount",
           "type":"uint256",
           "internalType":"uint256"
        }
     ],
     "outputs":[
        {
           "name":"",
           "type":"uint256",
           "internalType":"uint256"
        }
     ],
     "stateMutability":"view"
  },
  {
     "type":"function",
     "name":"calculateEggSell",
     "inputs":[
        {
           "name":"eggs",
           "type":"uint256",
           "internalType":"uint256"
        }
     ],
     "outputs":[
        {
           "name":"",
           "type":"uint256",
           "internalType":"uint256"
        }
     ],
     "stateMutability":"view"
  },
  {
     "type":"function",
     "name":"calculateTrade",
     "inputs":[
        {
           "name":"rt",
           "type":"uint256",
           "internalType":"uint256"
        },
        {
           "name":"rs",
           "type":"uint256",
           "internalType":"uint256"
        },
        {
           "name":"bs",
           "type":"uint256",
           "internalType":"uint256"
        }
     ],
     "outputs":[
        {
           "name":"",
           "type":"uint256",
           "internalType":"uint256"
        }
     ],
     "stateMutability":"pure"
  },
  {
     "type":"function",
     "name":"claimFromMine",
     "inputs":[
        
     ],
     "outputs":[
        
     ],
     "stateMutability":"nonpayable"
  },
  {
     "type":"function",
     "name":"compoundResources",
     "inputs":[
        
     ],
     "outputs":[
        
     ],
     "stateMutability":"nonpayable"
  },
  {
     "type":"function",
     "name":"depositIntoMine",
     "inputs":[
        {
           "name":"amount",
           "type":"uint256",
           "internalType":"uint256"
        },
        {
           "name":"referrer",
           "type":"address",
           "internalType":"address"
        }
     ],
     "outputs":[
        
     ],
     "stateMutability":"nonpayable"
  },
  {
     "type":"function",
     "name":"devFee",
     "inputs":[
        
     ],
     "outputs":[
        {
           "name":"",
           "type":"uint256",
           "internalType":"uint256"
        }
     ],
     "stateMutability":"view"
  },
  {
     "type":"function",
     "name":"getBalance",
     "inputs":[
        
     ],
     "outputs":[
        {
           "name":"",
           "type":"uint256",
           "internalType":"uint256"
        }
     ],
     "stateMutability":"view"
  },
  {
     "type":"function",
     "name":"getEggs",
     "inputs":[
        {
           "name":"_user",
           "type":"address",
           "internalType":"address"
        }
     ],
     "outputs":[
        {
           "name":"",
           "type":"uint256",
           "internalType":"uint256"
        }
     ],
     "stateMutability":"view"
  },
  {
     "type":"function",
     "name":"getEggsSinceLastHatch",
     "inputs":[
        {
           "name":"adr",
           "type":"address",
           "internalType":"address"
        }
     ],
     "outputs":[
        {
           "name":"",
           "type":"uint256",
           "internalType":"uint256"
        }
     ],
     "stateMutability":"view"
  },
  {
     "type":"function",
     "name":"getLiquidatableUsers",
     "inputs":[
        
     ],
     "outputs":[
        {
           "name":"_usersToLiquidate",
           "type":"address[]",
           "internalType":"address[]"
        },
        {
           "name":"_growAmounts",
           "type":"uint256[]",
           "internalType":"uint256[]"
        }
     ],
     "stateMutability":"view"
  },
  {
     "type":"function",
     "name":"getMiners",
     "inputs":[
        {
           "name":"_user",
           "type":"address",
           "internalType":"address"
        }
     ],
     "outputs":[
        {
           "name":"",
           "type":"uint256",
           "internalType":"uint256"
        }
     ],
     "stateMutability":"view"
  },
  {
     "type":"function",
     "name":"grow",
     "inputs":[
        
     ],
     "outputs":[
        {
           "name":"",
           "type":"address",
           "internalType":"address"
        }
     ],
     "stateMutability":"view"
  },
  {
     "type":"function",
     "name":"growFee",
     "inputs":[
        
     ],
     "outputs":[
        {
           "name":"",
           "type":"uint256",
           "internalType":"uint256"
        }
     ],
     "stateMutability":"view"
  },
  {
     "type":"function",
     "name":"initializeMiner",
     "inputs":[
        
     ],
     "outputs":[
        
     ],
     "stateMutability":"nonpayable"
  },
  {
     "type":"function",
     "name":"initialized",
     "inputs":[
        
     ],
     "outputs":[
        {
           "name":"",
           "type":"bool",
           "internalType":"bool"
        }
     ],
     "stateMutability":"view"
  },
  {
     "type":"function",
     "name":"liquidateUsers",
     "inputs":[
        {
           "name":"toLiquidate",
           "type":"address[]",
           "internalType":"address[]"
        }
     ],
     "outputs":[
        
     ],
     "stateMutability":"nonpayable"
  },
  {
     "type":"function",
     "name":"liquidatorFee",
     "inputs":[
        
     ],
     "outputs":[
        {
           "name":"",
           "type":"uint256",
           "internalType":"uint256"
        }
     ],
     "stateMutability":"view"
  },
  {
     "type":"function",
     "name":"marketEggs",
     "inputs":[
        
     ],
     "outputs":[
        {
           "name":"",
           "type":"uint256",
           "internalType":"uint256"
        }
     ],
     "stateMutability":"view"
  },
  {
     "type":"function",
     "name":"owner",
     "inputs":[
        
     ],
     "outputs":[
        {
           "name":"",
           "type":"address",
           "internalType":"address"
        }
     ],
     "stateMutability":"view"
  },
  {
     "type":"function",
     "name":"renounceOwnership",
     "inputs":[
        
     ],
     "outputs":[
        
     ],
     "stateMutability":"nonpayable"
  },
  {
     "type":"function",
     "name":"totalLiquidated",
     "inputs":[
        
     ],
     "outputs":[
        {
           "name":"",
           "type":"uint256",
           "internalType":"uint256"
        }
     ],
     "stateMutability":"view"
  },
  {
     "type":"function",
     "name":"transferOwnership",
     "inputs":[
        {
           "name":"newOwner",
           "type":"address",
           "internalType":"address"
        }
     ],
     "outputs":[
        
     ],
     "stateMutability":"nonpayable"
  },
  {
     "type":"function",
     "name":"user",
     "inputs":[
        {
           "name":"",
           "type":"address",
           "internalType":"address"
        }
     ],
     "outputs":[
        {
           "name":"miners",
           "type":"uint256",
           "internalType":"uint256"
        },
        {
           "name":"totalInvested",
           "type":"uint256",
           "internalType":"uint256"
        },
        {
           "name":"totalRedeemed",
           "type":"uint256",
           "internalType":"uint256"
        },
        {
           "name":"refEggs",
           "type":"uint256",
           "internalType":"uint256"
        },
        {
           "name":"lockedEggs",
           "type":"uint256",
           "internalType":"uint256"
        },
        {
           "name":"lastInteraction",
           "type":"uint256",
           "internalType":"uint256"
        },
        {
           "name":"referrer",
           "type":"address",
           "internalType":"address"
        }
     ],
     "stateMutability":"view"
  },
  {
     "type":"event",
     "name":"Deposit",
     "inputs":[
        {
           "name":"_user",
           "type":"address",
           "indexed":true,
           "internalType":"address"
        },
        {
           "name":"_ref",
           "type":"address",
           "indexed":true,
           "internalType":"address"
        },
        {
           "name":"_growAmount",
           "type":"uint256",
           "indexed":false,
           "internalType":"uint256"
        }
     ],
     "anonymous":false
  },
  {
     "type":"event",
     "name":"Initialize",
     "inputs":[
        {
           "name":"timeStamp",
           "type":"uint256",
           "indexed":false,
           "internalType":"uint256"
        }
     ],
     "anonymous":false
  },
  {
     "type":"event",
     "name":"Liquidation",
     "inputs":[
        {
           "name":"_liquidator",
           "type":"address",
           "indexed":true,
           "internalType":"address"
        },
        {
           "name":"_users",
           "type":"address[]",
           "indexed":false,
           "internalType":"address[]"
        },
        {
           "name":"_liquidationReward",
           "type":"uint256",
           "indexed":false,
           "internalType":"uint256"
        }
     ],
     "anonymous":false
  },
  {
     "type":"event",
     "name":"OwnershipTransferred",
     "inputs":[
        {
           "name":"previousOwner",
           "type":"address",
           "indexed":true,
           "internalType":"address"
        },
        {
           "name":"newOwner",
           "type":"address",
           "indexed":true,
           "internalType":"address"
        }
     ],
     "anonymous":false
  },
  {
     "type":"event",
     "name":"PriceAfterBurn",
     "inputs":[
        {
           "name":"_price",
           "type":"uint256",
           "indexed":false,
           "internalType":"uint256"
        },
        {
           "name":"_timestamp",
           "type":"uint256",
           "indexed":false,
           "internalType":"uint256"
        }
     ],
     "anonymous":false
  },
  {
     "type":"event",
     "name":"Redeem",
     "inputs":[
        {
           "name":"_user",
           "type":"address",
           "indexed":true,
           "internalType":"address"
        },
        {
           "name":"_growAmount",
           "type":"uint256",
           "indexed":false,
           "internalType":"uint256"
        }
     ],
     "anonymous":false
  },
  {
     "type":"event",
     "name":"Reinvest",
     "inputs":[
        {
           "name":"_user",
           "type":"address",
           "indexed":true,
           "internalType":"address"
        },
        {
           "name":"_growAmount",
           "type":"uint256",
           "indexed":false,
           "internalType":"uint256"
        }
     ],
     "anonymous":false
  },
  {
     "type":"error",
     "name":"GrowMiner__InvalidAmount",
     "inputs":[
        
     ]
  },
  {
     "type":"error",
     "name":"GrowMiner__NoEggs",
     "inputs":[
        
     ]
  },
  {
     "type":"error",
     "name":"GrowMiner__NotDeposited",
     "inputs":[
        
     ]
  },
  {
     "type":"error",
     "name":"GrowMiner__NotInitialized",
     "inputs":[
        
     ]
  },
  {
     "type":"error",
     "name":"GrowMiner__NothingToLiquidate",
     "inputs":[
        
     ]
  },
  {
     "type":"error",
     "name":"GrowMiner__OnlyIntegers",
     "inputs":[
        
     ]
  }
] as const;

export default abi;