const abi = [
  {
     "inputs":[
        {
           "internalType":"address",
           "name":"_token",
           "type":"address"
        },
        {
           "internalType":"address",
           "name":"_liqOut",
           "type":"address"
        },
        {
           "internalType":"address",
           "name":"_seed",
           "type":"address"
        },
        {
           "internalType":"address[]",
           "name":"_owners",
           "type":"address[]"
        }
     ],
     "stateMutability":"nonpayable",
     "type":"constructor"
  },
  {
     "inputs":[
        
     ],
     "name":"NGR_InvalidAmount",
     "type":"error"
  },
  {
     "inputs":[
        
     ],
     "name":"NGR__CannotLiquidate",
     "type":"error"
  },
  {
     "anonymous":false,
     "inputs":[
        {
           "indexed":true,
           "internalType":"address",
           "name":"user",
           "type":"address"
        },
        {
           "indexed":false,
           "internalType":"uint256",
           "name":"amount",
           "type":"uint256"
        },
        {
           "indexed":false,
           "internalType":"uint256",
           "name":"corp_position",
           "type":"uint256"
        }
     ],
     "name":"CorpDeposit",
     "type":"event"
  },
  {
     "anonymous":false,
     "inputs":[
        {
           "indexed":true,
           "internalType":"address",
           "name":"user",
           "type":"address"
        },
        {
           "indexed":false,
           "internalType":"uint256",
           "name":"amount",
           "type":"uint256"
        },
        {
           "indexed":false,
           "internalType":"uint256",
           "name":"position",
           "type":"uint256"
        },
        {
           "indexed":false,
           "internalType":"uint256",
           "name":"liquidationPosition",
           "type":"uint256"
        }
     ],
     "name":"CorpLiquidate",
     "type":"event"
  },
  {
     "anonymous":false,
     "inputs":[
        {
           "indexed":true,
           "internalType":"address",
           "name":"user",
           "type":"address"
        },
        {
           "indexed":false,
           "internalType":"uint256",
           "name":"amount",
           "type":"uint256"
        },
        {
           "indexed":false,
           "internalType":"uint256",
           "name":"indexPosition",
           "type":"uint256"
        }
     ],
     "name":"Deposit",
     "type":"event"
  },
  {
     "anonymous":false,
     "inputs":[
        {
           "indexed":true,
           "internalType":"address",
           "name":"user",
           "type":"address"
        },
        {
           "indexed":false,
           "internalType":"uint256",
           "name":"amount",
           "type":"uint256"
        },
        {
           "indexed":false,
           "internalType":"uint256",
           "name":"position",
           "type":"uint256"
        }
     ],
     "name":"Liquidate",
     "type":"event"
  },
  {
     "inputs":[
        
     ],
     "name":"MAX_DEPOSIT",
     "outputs":[
        {
           "internalType":"uint256",
           "name":"",
           "type":"uint256"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"MIN_DEPOSIT",
     "outputs":[
        {
           "internalType":"uint256",
           "name":"",
           "type":"uint256"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"USDT",
     "outputs":[
        {
           "internalType":"contract IERC20",
           "name":"",
           "type":"address"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"canLiquidate",
     "outputs":[
        {
           "internalType":"bool",
           "name":"",
           "type":"bool"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"corpPosition3",
     "outputs":[
        {
           "internalType":"address",
           "name":"owner",
           "type":"address"
        },
        {
           "internalType":"uint256",
           "name":"depositAmount",
           "type":"uint256"
        },
        {
           "internalType":"uint256",
           "name":"depositTime",
           "type":"uint256"
        },
        {
           "internalType":"uint256",
           "name":"liquidationTime",
           "type":"uint256"
        },
        {
           "internalType":"uint256",
           "name":"liquidationPosition",
           "type":"uint256"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"corpPosition4",
     "outputs":[
        {
           "internalType":"address",
           "name":"owner",
           "type":"address"
        },
        {
           "internalType":"uint256",
           "name":"depositAmount",
           "type":"uint256"
        },
        {
           "internalType":"uint256",
           "name":"depositTime",
           "type":"uint256"
        },
        {
           "internalType":"uint256",
           "name":"liquidationTime",
           "type":"uint256"
        },
        {
           "internalType":"uint256",
           "name":"liquidationPosition",
           "type":"uint256"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"corpWallet",
     "outputs":[
        {
           "internalType":"address",
           "name":"",
           "type":"address"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"cycleCounter",
     "outputs":[
        {
           "internalType":"uint256",
           "name":"",
           "type":"uint256"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"uint256",
           "name":"amount",
           "type":"uint256"
        }
     ],
     "name":"deposit",
     "outputs":[
        
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"depositCounter",
     "outputs":[
        {
           "internalType":"uint256",
           "name":"",
           "type":"uint256"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"uint256",
           "name":"amount",
           "type":"uint256"
        },
        {
           "internalType":"address",
           "name":"receiver",
           "type":"address"
        }
     ],
     "name":"depositForUser",
     "outputs":[
        
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"address",
           "name":"user",
           "type":"address"
        }
     ],
     "name":"getUserPositions",
     "outputs":[
        {
           "internalType":"uint256[]",
           "name":"",
           "type":"uint256[]"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"helixPrice",
     "outputs":[
        {
           "internalType":"uint256",
           "name":"",
           "type":"uint256"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"liqOutWallet",
     "outputs":[
        {
           "internalType":"address",
           "name":"",
           "type":"address"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"liquidate",
     "outputs":[
        
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"liquidationsCounter",
     "outputs":[
        {
           "internalType":"uint256",
           "name":"",
           "type":"uint256"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"uint256",
           "name":"",
           "type":"uint256"
        }
     ],
     "name":"owners",
     "outputs":[
        {
           "internalType":"address",
           "name":"",
           "type":"address"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"uint256",
           "name":"",
           "type":"uint256"
        }
     ],
     "name":"positions",
     "outputs":[
        {
           "internalType":"address",
           "name":"owner",
           "type":"address"
        },
        {
           "internalType":"uint256",
           "name":"depositAmount",
           "type":"uint256"
        },
        {
           "internalType":"uint256",
           "name":"depositTime",
           "type":"uint256"
        },
        {
           "internalType":"uint256",
           "name":"liquidationTime",
           "type":"uint256"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"totalDeposits",
     "outputs":[
        {
           "internalType":"uint256",
           "name":"",
           "type":"uint256"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"totalLiquidations",
     "outputs":[
        {
           "internalType":"uint256",
           "name":"",
           "type":"uint256"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"totalSupply",
     "outputs":[
        {
           "internalType":"uint256",
           "name":"",
           "type":"uint256"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"address",
           "name":"",
           "type":"address"
        },
        {
           "internalType":"uint256",
           "name":"",
           "type":"uint256"
        }
     ],
     "name":"userPositions",
     "outputs":[
        {
           "internalType":"uint256",
           "name":"",
           "type":"uint256"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"address",
           "name":"",
           "type":"address"
        }
     ],
     "name":"userStats",
     "outputs":[
        {
           "internalType":"uint256",
           "name":"totalDeposited",
           "type":"uint256"
        },
        {
           "internalType":"uint256",
           "name":"totalLiquidated",
           "type":"uint256"
        },
        {
           "internalType":"uint256",
           "name":"totalWithdrawn",
           "type":"uint256"
        },
        {
           "internalType":"uint256",
           "name":"totalPositions",
           "type":"uint256"
        },
        {
           "internalType":"uint256",
           "name":"totalPositionsLiquidated",
           "type":"uint256"
        },
        {
           "internalType":"uint256",
           "name":"totalPositionsWithdrawn",
           "type":"uint256"
        },
        {
           "internalType":"uint256",
           "name":"lastLiquidatedPosition",
           "type":"uint256"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"userToLiquidate",
     "outputs":[
        {
           "internalType":"uint256",
           "name":"",
           "type":"uint256"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  }
] as const;
export default abi;